print("we are about to calculate the area of a rectangle")
base = input("what is the base?:")
height = input("what is the height"?:")
area =int(base) * int(height)
print ("the area of the rectangle is {}".format(area))